### ISSUE TITLE
Mac port

### ISSUE THREAD

**Issue by jenduis** [Jumprocks1/drum-game#1]
Do you plan on porting this to Mac Os? An Arm64 Universal build would be perfect considering the already existing DtxPlayer port for Mac is suboptimal. Or any instructions for building myself would be appreciated, thank you.

**Comment by Jumprocks1** [comment]
Thank you for opening up an issue.

Everything should already work for macOS. All platforms with .NET 7 support (including Arm64) should work with the following instructions. I currently play on Linux using this method:

1. Install [.NET 7](https://dotnet.microsoft.com/en-us/download/dotnet/7.0) for your platform (macOS Arm64)
2. You can validate your .NET 7 install by running `dotnet version`. For me this currently outputs `7.0.101` - anything >7 will work.
3. Download [DrumGame-v0.3.0-net7.0.zip](https://github.com/Jumprocks1/drum-game/releases/download/v0.3.0/DrumGame-v0.3.0-net7.0.zip) from the release page.
4. Unzip the .zip file
5. Open a terminal inside `drum-game-net7.0`
6. Run `dotnet DrumGame.dll` - this should work on any platform, not just Windows

After running that command, the game should boot and mention that the resources folder needs to be downloaded (includes 135 maps, but no audio). After downloading that, the game should just work. You can then proceed to drag and drop any .zip, .dtx or set.def files into the game and it will convert them. To make the game easier to boot, you may want to create a shortcut for running the command `dotnet DrumGame.dll`. If you plan to play only DTXMania maps, you can put `tag=dtx` into the search bar.

I would like to make this an easier process, but I honestly have no clue how to properly ship apps for macOS or really any platform.

If you have any questions or issues please let me know. I haven't gotten to test the game on many other platforms, so I would greatly appreciate any feedback.
