### ISSUE TITLE
Fix references to osu Framework and the `ManagedBass.Midi` package

### ISSUE THREAD

**Issue by nathanpovo** [Jumprocks1/drum-game#4]
The [`README`](https://github.com/Jumprocks1/drum-game/blob/5ab61405709e4fc288e069a49d73d6c72912ca8a/DrumGame/README.md) contains the following documentation on running the project from source:

> As of 6-24-2024, the game is using [2024.523.0](https://www.nuget.org/packages/ppy.osu.Framework/2024.523.0) for the framework. The version directly from NuGet will not work since they switched to a fork of `ManagedBass`. To get it working, clone the correct version from [GitHub](https://github.com/ppy/osu-framework) and swap out the forked references for ManagedBass in `osu.Framework.csproj` so they look like this: `<PackageReference Include="ManagedBass" Version="3.1.0" />`. This is required because DrumGame uses the `ManagedBass.Midi` package, but the framework developers did not fork the MIDI package. This breaks many of the references when the forked version of ManagedBass is used. I would like to try fixing this in the future, but I couldn't figure out how to correct the reference errors.

This process makes it difficult to run the project from source, as it requires cloning an additional repository and manual changes to the framework's source code. This can be a barrier to entry for new contributors and users who want to run the project locally.

**Comment by Jumprocks1** [comment]
Do you have any suggestions for fixing this? The only one I am aware of is adding the framework project as a Git submodule.

**Comment by nathanpovo** [comment]
I did manage to fix it locally (in the process of creating a PR for it).

But I got distracted with the `.gitignore` and `.gitattributes` files and switched to handling those first 😅
